uploads = []
generated = []

[[outputs]]
id = "qcleGlS7w9EWtXHU1GwDv"
uri = "file://apj_build/android/app/build/outputs/apk/debug/app-debug.apk"
type = "unspecified"
title = "app-debug.apk"
description = "Direct binary download of the generated Android DEBUG APK."
logical_id = "6c024b3a-56a3-4680-be3e-800dcddaa792"
content_hash = "sha256:88c372eec08589c76c833e72d583888db4fef4a498e11e646a8af9395fb913bb"
size = 15251
mtime_ms = 1788141398334
storage_uri = "gcs://replit-rams-assets-sisko/rams/assets/repl:53c958ee-1d90-4194-97d2-c707ff32e6b7/6c024b3a-56a3-4680-be3e-800dcddaa792/22203340-ba34-42a3-bbca-aeb159aa60f8"
storage_version_token = "1788143260126325"
content_type = "application/octet-stream"
